module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  block: 0
  block_content: 0
  block_hello: 0
  breakpoint: 0
  cat_the_cat: 0
  category_rating: 0
  ckeditor: 0
  coffee: 0
  color: 0
  colorbox: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  flag: 0
  hello: 0
  help: 0
  history: 0
  image: 0
  kint: 0
  layout_plugin: 0
  like_dislike: 0
  like_message: 0
  link: 0
  menu_ui: 0
  my_custom_block: 0
  my_new_page: 0
  node: 0
  options: 0
  page_cache: 0
  panels: 0
  panels_ipe: 0
  path: 0
  quickedit: 0
  rdf: 0
  rules: 0
  search: 0
  shortcut: 0
  smtp: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  typed_data: 0
  update: 0
  user: 0
  views_load_more: 0
  views_ui: 0
  votemodule: 0
  webprofiler: 0
  menu_link_content: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
