smtp_on: true
smtp_host: smtp.gmail.com
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_username: sorikplius@gmail.com
smtp_password: '024251064'
smtp_from: sorikplius@gmail.com
smtp_fromname: sorikplius@gmail.com
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
_core:
  default_config_hash: fP57Sd8RjnZMVH3p_R-Yt0tC8j7Z-BuzGMIp6pmrHAI
